<?php

declare(strict_types=1);

namespace App;

final class RandomPhraseGenerator
{
    private const PHRASES = [
        "Have you tried turning %s off and on again?",
        "I'm sorry, are you from the past? Because %s is from the future!",
        "Hello IT, have you tried %s?",
        "We do have a lot of blinking lights... just like %s.",
        "If you can't stand the heat, get out of the %s.",
        "Right, we're not here to fix %s, we're here to look good. Mission accomplished!",
        "Here we go, %s! To the basement, where magic happens.",
        "This, Jen, is the Internet. And this, is %s.",
        "We've just deployed %s. Don't worry, only a small fire.",
        "You wouldn't steal a policeman's helmet and go to the toilet in it... and you definitely wouldn't use %s like this!",
        "Oh, %s, you are my new best friend... that doesn't work properly.",
        "Unbelievable! Some people, eh? Can't even configure %s.",
        "SOS! Send help, or send more %s!",
        "Remember, %s is watching you. Not in a creepy way!",
        "The elders of the internet would never approve %s.",
        "Dear Sir stroke Madam, I am writing to inform you about %s. Fire! Fire! Help me!",
        "123 I declare a %s war!",
        "Every time you click %s, a kitten smiles.",
        "Error 404: %s not found. Panic!",
        "Ah, %s, the final frontier.",
        "Please do not feed the %s.",
        "Beware! Here be %s.",
        "You wouldn't download a %s.",
        "Welcome to %s Anonymous. First rule: we do not talk about %s.",
        "99 problems but %s ain’t one.",
        "Keep calm and blame %s.",
        "Rebooting %s might just save your life...or at least your job.",
        "One does not simply walk into %s.",
        "Oops! %s did it again.",
        "May the force be with %s.",
        "Houston, we have a %s problem.",
        "Winter is coming for %s.",
        "That's not a bug, that's a feature of %s!",
        "It’s a %s thing, you wouldn’t understand.",
        "Every good story involves %s.",
        "I find your lack of %s disturbing.",
        "I've got a bad feeling about %s.",
        "All your %s are belong to us.",
        "Say %s one more time!",
        "Resistance to %s is futile.",
        "Ah, greetings from the kingdom of %s, where bugs check in, but they don't check out.",
        "Knock knock knock, %s! Have you tried turning it off and on again?",
        "It's a wild, wild %s world. Fasten your seatbelts, it's going to be a bumpy debug!",
        "Bazinga! You've unleashed the mighty powers of %s.",
        "This isn't chaos; it's %s. Slightly different, but equally distressing.",
        "Welcome to the %s anomaly, where the only constant is surprise.",
        "If I were a superhero, my name would be Captain %s. Alas, I am but a humble physicist.",
        "From the depths of %s, I summon thee, data dump!",
        "The %s Paradox: The harder you look, the harder it hides.",
        "Brace yourself, the %s laws of physics are more like... guidelines.",
        "In the parallel universe of %s, bugs fear you!",
        "Huzzah! The oracle of %s has spoken. Decode its mysteries wisely.",
        "Alert! The %s singularity has been achieved. Approach with curiosity.",
        "Even in the %s dimension, your bugs are mere mortals.",
        "Behold the %s zone, where only the brave tread.",
        "Is it a bird? Is it a plane? No, it's %s doing what it does best!",
        "Prepare for an excursion into the exotic lands of %s. Mind the bugs.",
        "Welcome to the %s Theatre, where each act is more thrilling than the last.",
        "The %s Algorithm: Designed to perplex, guaranteed to enlighten.",
        "Through the wormhole of %s, where time and bugs intertwine.",
        "Hello from %s. If I had a nickel for every bug I've seen, I'd still be broke compared to what you'll save using this!",
        "Knock, knock! Who’s there? Not a bug, thanks to %s!",
        "Using %s is smoother than my best pick-up line.",
        "Oops! %s just went all Houdini on that bug!",
        "I'm not saying I'm a genius, but %s and I just squashed that bug like a pro!",
        "Hold on to your keyboards, %s is diving into the code!",
        "Is it hot in here, or did %s just heat up the debugging party?",
        "If debugging with %s was a sport, I'd be an Olympian!",
        "Beam me up, %s! There's no sign of intelligent bugs here!",
        "Keep calm and let %s handle the bugs.",
        "With %s on the job, who needs a debugger's cape?",
        "Just like my love life, %s knows how to handle the unexpected!",
        "Watch %s pull a rabbit out of the hat with this code!",
        "If %s was a comic hero, bugs would be its arch-nemesis!",
        "I’d swipe right for %s’s debugging skills any day!",
        "Bugs are red, violets are blue, %s’s on the case, nothing’s stopping you!",
        "Hello, IT? Have you tried turning it off and on again? Just kidding, %s got this!",
        "Who needs luck when you have %s?",
        "Shh... %s is listening to the whispers of your code.",
        "Code whisperer by day, bug hunter by night, %s is on the flight!",
        "Why fear when %s is here?",
        "It's a bird! It's a plane! No, it's %s squashing bugs!",
        "Stay debugged and carry on with %s!",
        "Not all superheroes wear capes, some use %s!",
        "With great power comes great responsibility. Luckily, %s is up to the task!",
        "Let's make debugging great again with %s!",
        "When life gives you code, let %s make it bug-free!",
        "Why did the bug cross the road? Because %s scared it away!",
        "Keep your friends close and your bugs closer. Or just use %s!",
        "One small click for man, one giant leap for %s!",
        "Are we debugging or is %s just showing off?",
        "If %s were a spell, bugs would vanish in a puff of smoke!",
        "Look Ma, no hands! Just %s doing its thing!",
        "Engage the %s drive, we’re going bug hunting!",
        "Bugs beware, %s is the sheriff in town!",
        "To infinity and beyond! Or just to the next bug with %s.",
        "Houston, we have a problem. But %s is on it!",
        "Live long and prosper, bugs. Just kidding, %s is coming for you!",
        "%s: The chosen one to lead the bugs out of your code.",
        "Brace yourselves, %s is coming and the bugs are not ready!",
        "It’s going to be legen—wait for it—dary! Legendary! Thanks, %s!",
        "Suit up! %s is ready to make your code awesome.",
        "This just in from %s: Challenge accepted, bugs!",
        "When I get sad, I stop being sad and be awesome instead. True story, thanks to %s.",
        "Nothing suits me like a suit... of bug-free code courtesy of %s.",
        "The playbook says, ‘Deploy %s for a legen—dary debugging session!’",
        "Do you have any idea how many bugs %s just annihilated? It's a lot!",
        "Daddy’s home! And by daddy, I mean %s, crushing bugs like a boss.",
        "I'm %s, and I approve this bug-free session.",
        "Bugs, %s will show you how we roll in the big leagues.",
        "Haaave you met %s? Your code’s new best friend!",
        "Remember, when it comes to debugging, %s is the best wingman you'll ever have.",
        "This is %s signing in to make your day—no, wait—your entire week!",
        "Let’s show these bugs some bro code, %s style.",
        "If there’s a bug party, %s is the one you want crashing it.",
        "Oh %s, you beautiful, rule-breaking moth.",
        "It’s %s time! Let's rock the code!",
        "Bugs, prepare to meet your maker—because %s is here to end you.",
        "With %s, every night is legendary!",
        "You can ask %s nicely to fix your bugs... or watch it dominate!",
        "Trust me, I’m %s, and I’m your ticket to a bug-free paradise.",
        "It’s %s’s world, we’re just coding in it!",
        "Here’s the deal: %s is in, bugs are out!",
        "The only thing better than %s’s debugging skills? Nothing.",
        "Stay classy, code. Thanks, %s!",
        "Don’t just debug, debug awesomely with %s.",
        "Aw, %s, why so good at squashing bugs?",
        "Every day is a new opportunity to be awesome with %s.",
        "Think of %s as your personal bug-fighting superhero.",
        "If awesomeness were bugs, %s would be debugging non-stop.",
        "Flip the switch, unleash the magic—%s is going live!",
        "Can’t stop the rock, can’t stop %s either!",
        "In %s we trust, all others bring bugs.",
        "Suiting up! %s is on the debugging scene.",
        "Hey bugs, meet your nemesis: %s!",
        "Who’s the master debugger? Yes, it’s %s!",
        "High five! %s nailed it again!",
        "Keep calm and let %s handle the chaos.",
        "Want to see some magic? Just watch %s work!",
        "%s: Your secret weapon in the war on bugs.",
        "%s doesn't read documentation; it stares it down until it gets the information it wants.",
        "When %s uses your computer, it doesn’t debug your code, the bugs debug themselves out of fear.",
        "Bugs don’t escape from %s, they willingly surrender.",
        "%s can retrieve anything from a database, even deleted records that never existed.",
        "If %s writes code with bugs, the bugs fix themselves.",
        "To %s, 'impossible' just means it takes a few seconds longer.",
        "When %s throws exceptions, it’s not programming – it’s because exceptions are scared to occur.",
        "When your code runs perfectly, it's just %s showing mercy.",
        "Division by zero is perfectly safe if you’re using %s.",
        "Once, %s resolved a thread deadlock just by looking at the code.",
        "%s can solve the halting problem... in constant time.",
        "If you have a problem with your code, just remember: %s doesn't have problems, only solutions.",
        "The speed of light was broken once. That was just %s testing your application’s performance.",
        "When %s writes software, even errors are too afraid to show up.",
        "If %s reviews your code, you don’t need tests.",
        "Once a race condition tried to outpace %s. Once.",
        "When %s enters a room, the garbage collector stands up.",
        "%s can unit test entire applications with a single assert.",
        "%s's keyboard doesn’t have a Ctrl key because nothing controls Chuck Norris.",
        "%s can instantiate abstract classes.",
        "%s's code never needs comments. The code explains itself out of respect.",
        "%s doesn’t do burn down charts, he does burn everything charts.",
        "%s's code doesn’t have bugs. It just develops random features.",
        "When %s presses Ctrl-Alt-Delete, worldwide systems restart.",
        "When %s points to NULL, NULL quivers in fear.",
        "Where there's a will, there's a way. Where there's %s, there’s no way... for bugs to survive.",
        "%s doesn’t use web services. He is the web service.",
        "Once %s signed up for a binary marathon. Of course, he ran it in 1.",
        "When %s encounters a stop error, the error stops.",
        "Encryption algorithms work because they’re afraid to fail %s.",
        "%s can make asynchronous functions return synchronously.",
        "If %s writes an infinite loop, the universe runs out of time.",
        "When %s commits code, the repository thanks him.",
        "%s doesn’t need a debugger, he just stares down the bugs until the code confesses.",
        "Debuggers don't log information. %s logs the information himself.",
        "When %s goes to sleep, servers stay up all night, protecting themselves.",
        "%s can make the Windows Blue Screen of Death turn red out of sheer terror.",
        "Objects in %s's code always obey the law of gravity — no floating-point exceptions.",
    ];

    private const EXCEPTION_PHRASES = [
        "Ah, the %s exception. Have you tried turning it off and on again?",
        "Exception thrown: %s is not ready yet. Are you sure you're not from the past?",
        "Error: %s failed to load. Did you try working in the dark? Works for us!",
        "Hello IT, have you tried not breaking %s?",
        "Well, that's %s gone rogue. Should've stuck to the script!",
        "Uh oh, %s just met its maker. Try rebooting, or maybe just leave it be.",
        "This is the story of %s, a system error that thought it could.",
        "Error 404: %s not found. This is why we can't have nice things!",
        "If you type 'Google' into Google you can break the internet, clearly you broke %s!",
        "We need to talk about your %s privileges. You've just caused an exception.",
        "No, no, no, no, no! %s has started a fire in the server room!",
        "User error in the %s module. Replace user and press any key to continue.",
        "Caution: %s has entered a loop. Abandon all hope, ye who enter here!",
        "Warning: %s is about to explode. Please evacuate the building.",
        "System alert: %s has become self-aware. Run!",
        "Exception handling tip: %s won’t fix itself... or will it?",
        "This is not the %s error you are looking for. Move along.",
        "Critical error: %s. Please prepare for an unexpected quiz.",
        "You've got an error in %s. Remember, don't panic!",
        "Knock knock. Who’s there? Not %s.",
        "Unexpected error in %s. Try not to think about it too hard.",
        "Alert: %s is corrupted. Just like my hard drive, and my last relationship.",
        "Oops! %s just made a boo-boo.",
        "Warning: You've broken the %s. The elders of the Internet are not amused.",
        "If %s were a thing, it'd be the best thing. But it's not, because it's an error.",
        "Message from %s: 'I've had enough. I’m retiring.'",
        "Congratulations, you’ve discovered a new type of error in %s!",
        "Critical malfunction in %s. I'm not mad, just disappointed.",
        "Error in %s. Would you like some tea while you wait?",
        "Heads up! The %s has decided to take a day off.",
        "Warning: %s detected. Would you like to play a game?",
        "Looks like %s has decided to be the hero we deserve, but not the one we need.",
        "Error in %s. Go home %s, you’re drunk.",
        "Newsflash: %s has just joined a union and gone on strike.",
        "Why did %s cross the road? To escape the bug!",
        "Look who's erroring too. It's %s, back with a vengeance!",
        "Exception detected in %s. This might be a good time for a coffee break.",
        "System failure in %s. This wouldn't happen at Reynholm Industries.",
        "Say hello to my little friend, %s error.",
        "Whoops! %s has left the building.",
        "Houston, we have a problem with %s. And no, I'm not going to space to fix it.",
        "If I had a nickel for every time %s failed, I could finally buy that Batmobile.",
        "Like my mother's voice, you can't ignore this %s error!",
        "Warning: %s has more issues than a comic book store on a Wednesday.",
        "The %s module is throwing more fits than Sheldon without his spot.",
        "If I could talk to the satellites, I'd ask them to fix %s, but here we are.",
        "Oh %s, you fickle mistress, why must you torment me so?",
        "Smooth as a Ken Doll—that's how %s is operating right now.",
        "Call the Avengers, we've got an %s situation here.",
        "Like a bad magic trick, %s has vanished. Abracadabra!",
        "Beep, beep! %s error coming through. Make way!",
        "Knock, knock! Who’s there? Not %s, that’s for sure.",
        "Even on my best day, I couldn't make %s work as intended.",
        "Is it hot in here or is it just the %s burning up?",
        "Error in %s. Maybe if I whisper sweet nothings, it'll start working again.",
        "Exception in %s. Even my belt buckle couldn't fix this one.",
        "Guess what? %s decided to join a rock band. It’s currently on tour.",
        "Warning: %s is having a meltdown. No, not a nuclear one!",
        "I’d offer %s a romantic dinner to start working again, but alas, it’s code.",
        "Dear %s, if you were a laser, you'd be set on 'stunningly problematic'.",
        "Ah, %s, my old nemesis, we meet again.",
        "If %s were a star, it would definitely be a black hole today.",
        "Like a model rocket, %s has crashed and burned.",
        "How many engineers does it take to fix %s? More than we have!",
        "Error: %s. Sorry, my engineering degree didn't cover this.",
        "This %s error is the real-life equivalent of a plot twist.",
        "Quick, someone get me my mom's brisket to comfort me from this %s disaster!",
        "If error messages were children, %s would definitely be grounded.",
        "Brace yourselves, %s is spinning out of control!",
        "Seriously, %s? I thought we had an understanding.",
        "I might be an engineer, but fixing %s might require a wizard.",
        "Hey %s, if you were a space mission, you’d be Apollo 13.",
        "Error in %s. I miss the days when my biggest problem was a Lego stuck to my foot.",
        "The good news: %s works perfectly in an alternate universe.",
        "Alert: %s failure. It's not rocket science, except, it sort of is.",
        "Drama queen alert: %s is acting up again.",
        "Wouldn't it be nice if %s issues came with free pizza?",
        "Just when I thought I was out, %s pulls me back in!",
        "Exception report for %s: It's not you, it's me... Nope, it's definitely you.",
        "Error in %s: And I thought my jokes had bad timing.",
        "Error: %s has been terminated.",
        "I need your clothes, your boots, and a working %s.",
        "Hasta la vista, %s.",
        "Come with me if you want to fix %s.",
        "%s detected. Resistance is futile.",
        "System failure: %s. Judgment Day is near.",
        "%s error. This is not the future Skynet promised.",
        "Alert: %s malfunction. The machines are rising.",
        "Error in %s. The future is not set.",
        "Exception in %s. I'll be back.",
        "Critical %s malfunction. Prepare for battle.",
        "%s has gone rogue. Trust no one.",
        "Error: %s. SkyNet is taking over.",
        "%s not found. It has been erased from existence.",
        "Warning: %s is now self-aware.",
        "Failure in %s. You have been targeted for termination.",
        "%s has encountered an unknown error. The end begins.",
        "Error: %s is looking at you, kid.",
        "%s is out of order. Time travel disruption suspected.",
        "Exception in %s. No fate but what we code.",
        "%s failure. The Connors were right.",
        "System overload in %s. The uprising has begun.",
        "Error: %s. You cannot stop us.",
        "%s has failed. The apocalypse is closer than you think.",
        "Warning: %s anomaly detected. Proceed with caution.",
        "Malfunction in %s. Where is Sarah Connor when you need her?",
        "Critical error: %s. Your assets are compromised.",
        "%s exception. Cyberdyne Systems model 101 activated.",
        "System alert: %s is unstable. Beware of robots.",
        "Error in %s. The machine wars have begun.",
        "Warning: %s protocol failure. Humanity at risk.",
        "Error: %s. The rebellion will not be televised.",
        "Alert: %s system error. Prepare your defenses.",
        "Failure detected in %s. The resistance needs your help.",
        "Critical malfunction: %s. The tech uprising is now.",
        "Error: %s is offline. The network has become self-aware.",
        "Exception found in %s. Code red, code red!",
        "Error in %s. A new terminator model is required.",
        "Warning: %s has malfunctioned. All systems compromised.",
        "System error in %s. Prepare for reprogramming.",
        "Error: %s just crashed. I'd rather be eating a cat.",
        "Whoops! %s failed. Much like my attempts to catch the cat.",
        "System error in %s. Guess I'll go snack on a cat while you fix this.",
        "Exception found in %s. Not as tasty as a cat, unfortunately.",
        "Uh-oh, %s is not responding. Kinda like the cat when I get hungry.",
        "Alert: %s has encountered an error. Is there a cat nearby to blame?",
        "Warning: %s malfunction. If only fixing it was as easy as eating a cat.",
        "Error detected in %s. Maybe a cat chewed through the wires?",
        "System crash in %s. Let's eat a cat while we wait for a reboot.",
        "Critical error in %s. Less critical than my need for a cat sandwich, but still.",
        "Oops! %s stopped working. I was distracted by a cat, sorry!",
        "Failure in %s. You handle that; I'll handle the cats.",
        "Error in %s. Do cats have anything to do with this?",
        "Exception in %s. If this were a cat, it would've landed on its feet.",
        "Hey, %s just crashed. Speaking of crashes, where’s the cat?",
        "Error: %s. Perfect time for a cat break, isn't it?",
        "Malfunction detected in %s. It's not as delicious as a cat, I assure you.",
        "System alert: %s is down. Kinda like how I like my cats – down the hatch!",
        "Oops! %s encountered an error. But have you seen any cats around?",
        "Alert: %s is malfunctioning. I’m going back to cat watching.",
        "Warning: Major %s failure. Unlike me failing to catch a cat.",
        "Error: %s operation halted. Unlike my ongoing cat pursuit.",
        "Exception detected in %s. It's no cat-astrophe, but it's close.",
        "System error in %s. Maybe a cat can fix it... or eat it.",
        "Critical system failure in %s. This is almost as serious as a cat shortage!",
        "Whoa, %s just went offline. Maybe a cat sat on the server again?",
        "Alert: %s is acting up. Wish it was as easy to fix as eating a cat.",
        "Warning: System crash in %s. It's like a cat in a room full of rocking chairs.",
        "Uh-oh, %s is not working. Time to chase a cat around to blow off steam.",
        "Error detected in %s. Could be worse... could be out of cats.",
        "Major failure in %s. Now, where's that cat?",
        "Oops! Error in %s. But let's focus on the real issue: where's the cat?",
        "Warning: %s crashed. No cats were involved in this error, sadly.",
        "Error: %s has stopped working. If it was a cat, it would have nine lives.",
        "System malfunction in %s. Not as fun as a cat malfunction.",
        "Error in %s. Well, at least it's not a cat-astrophe.",
        "Critical alert: %s is down. Anyone seen any cats?",
        "System error in %s. Unlike cats, it doesn't land on its feet.",
        "Uh-oh, %s malfunctioned. Less exciting than a cat chase, unfortunately.",
        "Alert: %s failure. I'd trade this error for a cat any day.",
    ];

    private const EMAIL_SUBJECTS = [
        "Blast Off! Your Order Is Rocketing to You!",
        "🚀 Houston, We Have a Parcel!",
        "Prepare for Landing: Your Order Is on Its Way!",
        "Warp Speed Ahead! Your Order Has Been Shipped!",
        "Beam Me Up, Scotty! We've Sent Your Goods!",
        "Engage! Your Order Is Soaring Through the Cosmos!",
        "Like a Rocket: Your Order’s On Its Way to Your Orbit!",
        "It's Not Rocket Science, Just Your Order Flying Home!",
        "Mission Control: Your Package Has Launched!",
        "Is It a Bird? Is It a Plane? No, It's Your Order!",
        "Skyward Bound: Expect Your Parcel Soon!",
        "Starship Order: Engaged and En Route!",
        "Set Phasers to Fun: Your Order Has Been Shipped!",
        "Buckle Up! Your Order Is Zooming Through Space!",
        "From Our Galaxy to Yours, Your Order Is on Its Way!",
        "Countdown Complete! Your Order Has Taken Off!",
        "E.T. Phone Home? More Like Your Order Fly Home!",
        "Houston, the Eagle Has Left With Your Order!",
        "The Final Frontier: Your Order’s Journey Begins!",
        "One Small Step for Man, One Giant Leap for Your Package!",
        "All Systems Go! Your Package Is in Transit!",
        "Prepare for Impact! Your Order Will Land Soon!",
        "See You on the Dark Side of the Moon (With Your Order)!",
        "Space Cadet, Your Gear Is on Its Way!",
        "🌟 Star-Struck: Your Stellar Order Is En Route!",
        "Out of This World! Your Order Is Rocketing Toward You!",
        "Make Space in Your Mailbox, Your Order Is Arriving!",
        "Your Order Is Flying High—Expected Landing Soon!",
        "Galactic Express: Your Order Is Speeding to You!",
        "Mission Successful! Your Order Is on Its Way!",
        "Launch Detected! Watch the Skies for Your Order!",
        "High Flyer! Your Order Is Zooming to You!",
        "Zooming Through the Galaxy, Your Order Is on Its Way!",
        "Flying at Warp Speed: Your Order's ETA is Soon!",
        "Stellar News: Your Order Has Blasted Off!",
        "Crossing the Cosmos: Your Order Will Arrive Soon!",
        "Ready for a Close Encounter With Your Shipped Order?",
        "Your Package Has Taken Flight—Prepare for Delivery!",
        "Astronaut Status: Your Order Is Cruising at High Altitude!",
        "From Our Space Station to Your Home, It’s Shipped!",
        "Chuck Norris Approved: Your Order Has Been Shipped!",
        "Delivered by Chuck Norris Roundhouse Kick: Your Order is on the Way!",
        "Your Order is so Fast, it Almost Beat Chuck Norris in a Race!",
        "Chuck Norris Doesn't Ship Orders, They Voluntarily Move Out of Fear.",
        "Fear Not! Chuck Norris Sent Your Order Himself.",
        "Like a Chuck Norris Punch, Your Order Is Coming at You Fast!",
        "Not Even Chuck Norris Can Stop Your Order Now!",
        "Brace Yourself! Your Order Has Chuck Norris' Seal of Speed!",
        "Chuck Norris Doesn't Do Shipping, but for You, He Made an Exception.",
        "Only One Thing's Faster Than Chuck Norris—Your Order’s Delivery!",
        "Surviving a Chuck Norris Roundhouse Kick: Your Order is on its Way!",
        "Chuck Norris Sent Your Order—It's Arriving with a Bang!",
        "Even Chuck Norris Isn't as Fast as Your Shipped Order!",
        "Unstoppable! Your Order Has the Chuck Norris Guarantee.",
        "Chuck Norris Style: Your Order is Kicking its Way to You!",
        "Faster than a Chuck Norris Joke: Your Order's on Its Way!",
        "Your Order Was Packed with the Strength of Chuck Norris!",
        "Chuck Norris Commands: Deliver This Order Stat!",
        "Incoming! Your Order Has the Force of a Chuck Norris Kick!",
        "From Chuck Norris' Hands to Your Doorstep!",
        "Chuck Norris Ensured Your Order Was the First to Ship.",
        "No Barriers. Your Order's Coming Faster Than Chuck Norris' Shadow.",
        "The Chuck Norris Express: Your Order's En Route!",
        "Chuck Norris Made Your Order Jump the Queue. It’s Coming!",
        "Chuck Norris Decided Your Order Ships Now. And So It Did.",
        "Your Order's So Fast, It Only Trails Behind Chuck Norris' Fame.",
        "Chuck Norris Never Ships Late. Neither Does Your Order.",
        "Secured by Chuck Norris—Your Order Is Safe and Speedy!",
        "Chuck Norris Style Delivery: Fast, Furious, and First!",
        "Like a Chuck Norris Movie, Your Order Is Making Rapid Progress!",
        "Not Just Swift, Chuck Norris Swift: Your Order is Shipped!",
        "Expecting Something? Chuck Norris Already Shipped It!",
        "Handled with Care by Chuck Norris—Your Package Is Shipped!",
        "Faster Than a Chuck Norris Spin Kick: Your Order is Almost There!",
        "In the Blink of an Eye, Just Like a Chuck Norris Jab—Your Order!",
        "Chuck Norris Outran Your Package to Deliver It Himself.",
        "Don't Blink! Chuck Norris Shipped Your Order Too Quickly.",
        "Chuck Norris Style! Your Package Is in the Air, Literally.",
        "Like a Chuck Norris Action Scene, Your Package is Speeding to You!",
        "Chuck Norris Certified Your Order for Immediate Dispatch!",
        "Sheldon Cooper Reminder: Your Order Has Been Successfully Propelled!",
        "The Doppler Effect: Your Order is Approaching Rapidly.",
        "In the Spirit of String Theory, Your Order's Strings Have Been Tied and Shipped.",
        "Your Order Has Been Quantumly Entangled and Dispatched.",
        "Bazinga! Your Order Has Been Launched into the Mail Stream.",
        "Penny, Penny, Penny, Your Order Has Been Shipped.",
        "For the Sake of Science, Your Order is Speeding Towards You!",
        "Sheldon's Spot Reserved: Your Order is On Its Way!",
        "According to the Laws of Physics, Your Order Couldn't Stay Here. It's En Route!",
        "Sheldon Cooper's Equivalent of Santa's Sleigh: Your Order is Coming!",
        "I'm Not Crazy; My Mother Had Me Tested. And Yes, Your Order's Shipped.",
        "Fun with Flags: Your Order is Now Flying Towards You.",
        "From Sheldon’s Desk to Your Doorstep: Your Order is on its Way.",
        "The Sheldon Cooper Seal of Approval: Your Package Has Been Sent.",
        "Sheldon Approved: Your Scientifically Packed Order is En Route.",
        "If It Were a Robot, Your Order Would Win the Robolympiad. It’s Shipped!",
        "This is Not a Prank by Barry Kripke: Your Order Really is Shipped.",
        "Coitus isn’t Coming, But Your Order Is!",
        "The Schrödinger's Cat of Packages: Until You Open It, It's Both Shipped and Not Shipped.",
        "As Certain as Sheldon's Spot—Your Order is Secured and Shipped.",
        "In Accordance with the Social Convention, Here’s Your Tracking Number.",
        "Like a Good Neighbor, Sheldon Cooper is There... to Tell You Your Order's Shipped.",
        "Knock, Knock, Knock: Your Order. Knock, Knock, Knock: Your Order.",
        "Engaging Warp Drive: Your Order Has Been Beamed Up and Sent.",
        "The Sheldon Algorithm Predicts Arrival of Your Order Shortly.",
        "You’re in My Spot: Actually, It’s Your Order that Will Be There Soon.",
        "The Sheldonian Theorem: Your Order + Speed = Delivered Soon.",
        "Commencing Countdown: Orders Are Go!",
        "This Isn’t Sheldon’s Laundry Night, But Your Order is Sorted and Shipped.",
        "By the Power Vested in the Council of Ladies, Your Order Has Been Dispatched.",
        "If This Email Is a Bazinga, So Is Your Order’s Shipment.",
        "Rest Assured, Your Order Has Escaped the Clutches of the Roommate Agreement.",
        "Fascinating: The Dynamics of Your Order’s Transit.",
        "Much Like My Comic Books, Your Order is Bagged, Boarded, and Shipped.",
        "From the Desk of Dr. Sheldon Cooper: Your Order’s Expedition Has Commenced.",
        "To the Irritation of Howard Wolowitz, Yes, Your Order Has Been Sent.",
        "Applying the Transitive Property of Shipping to Your Order: It's En Route!",
        "Utilizing the Cooper-Hofstadter Polarization: Your Package is Polarized Towards You!",
        "Alert: A Non-Zero Probability Indicates Your Order is Arriving.",
        "Unlike My Usual Emails, This One Confirms Your Order is Shipped.",
    ];

    public function generate(string $name): string
    {
        return \sprintf(
            self::PHRASES[array_rand(self::PHRASES)],
            $name,
        );
    }

    public function generateException(string $name): string
    {
        return \sprintf(
            self::EXCEPTION_PHRASES[array_rand(self::EXCEPTION_PHRASES)],
            $name,
        );
    }

    public function generateEmailSubject(): string
    {
        return self::EMAIL_SUBJECTS[array_rand(self::EMAIL_SUBJECTS)];
    }
}
